version: '3'

tasks:
  build:
    cmds:
      - ./mvnw --batch-mode clean verify
  package:
    cmds:
      - ./mvnw --batch-mode clean package
  run:
    cmds:
      - ./mvnw spring-boot:run
#      - java -jar target/spring-0.0.1-SNAPSHOT.jar
    env:
      JAVA_HOME: /opt/homebrew/Cellar/openjdk/25/libexec/openjdk.jdk/Contents/Home
      DATABASE_HOST: localhost:5433
      DATABASE_NAME: dojo.spring
      DATABASE_USERNAME: manoj.baishya
      DATABASE_PASSWORD: postgres
      SERVER_PORT: 5987
