version: '3'

tasks:
  build:
    cmds:
      - ./mvnw verify
  run:
    cmds:
      - ./mvnw spring-boot:run
    env:
      DATABASE_HOST: DATABASE_HOST
      DATABASE_NAME: DATABASE_NAME
      DATABASE_USERNAME: DATABASE_USERNAME
      DATABASE_PASSWORD: DATABASE_PASSWORD
      SERVER_PORT: SERVER_PORT
