version: '3'

tasks:
  run:
    cmds:
      - ./mvnw spring-boot:run
    env:
      SERVER_PORT: 5000
      DATABASE_HOST: DATABASE_HOST
      DATABASE_NAME: dojo.spring
      DATABASE_USERNAME: DATABASE_USERNAME
      DATABASE_PASSWORD: DATABASE_PASSWORD
