CREATE TABLE public.departments
(
    id      int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    address varchar(255)                                                                                                             NULL,
    code    varchar(50)                                                                                                              NULL,
    "name"  varchar(255)                                                                                                             NOT NULL,
    CONSTRAINT departments_pkey PRIMARY KEY (id)
);

CREATE TABLE public.transactions
(
    id            int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    amount        numeric(38, 2)                                                                                                           NOT NULL,
    department_id int8                                                                                                                     NULL,
    CONSTRAINT transactions_pkey PRIMARY KEY (id)
);

ALTER TABLE public.transactions
    ADD CONSTRAINT fksf3gtcy1h8ur2hhy8m0nnj2so FOREIGN KEY (department_id) REFERENCES public.departments (id);
