name: Build and test manojbaishya/dojo.spring

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
          architecture: x64
      - name: Build and test
        run: ./mvnw -batch-mode clean verify
      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Copy Artifacts
        run: mkdir staging && cp target/*.jar staging
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dojo.spring.jar
          path: staging
